repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        files: ^(tests/(services|factories)/.*\.py|tests/conftest\.py)$
      - id: ruff-format
        files: ^(tests/(services|factories)/.*\.py|tests/conftest\.py)$

  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        files: ^(tests/(services|factories)/.*\.py|tests/conftest\.py)$

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        stages: [manual]
        additional_dependencies:
          - types-requests==2.32.0.20241016
        args:
          - --config-file=pyproject.toml
          - tests/services
          - tests/factories
          - tests/conftest.py

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier
        files: ^frontend/src/.*\.(js|css|html)$
