[tool.black]
line-length = 100
target-version = ["py311"]

[tool.isort]
profile = "black"
line_length = 100
known_first_party = ["app", "tests"]
skip_glob = ["migrations/**"]

[tool.ruff]
line-length = 100
target-version = "py311"
src = ["app", "tests"]
extend-exclude = ["migrations"]

[tool.ruff.lint]
select = ["E", "F", "I", "B", "UP", "W"]
ignore = ["E203"]

[tool.ruff.lint.per-file-ignores]
"tests/*" = ["S101"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false

[tool.mypy]
python_version = "3.11"
packages = ["app", "tests"]
ignore_missing_imports = true
strict_optional = true
warn_return_any = true
warn_unused_configs = true
warn_unused_ignores = true
